name: aeproject

on:
  push:
    paths: ['contract/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.x
      - run: |
          cd contract
          npm ci
          npx aeproject env --nodeVersion v6.6.0 --compilerVersion v6.1.0 && sleep 3
          npx aeproject test
